export const ACTION_CREATER = {
  ADD: "ADD",
  DELETE: "DELETE",
  MOVEUP: "MOVEUP",
  MOVEBOTTUM: "MOVEBOTTUM",
  UPDATE: "UPDATE",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
  RESET: "RESET",
  FETCH_USERS: "FETCH_USERS",
};
